

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: cybersec-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root  # ensures Jenkins can access docker.sock
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # needed for Jenkins to use Docker
      - ./jenkins:/var/jenkins_home/workspace/security-pipeline
    networks:
      - security-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: cybersec-portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - security-network

volumes:
  jenkins_home:
  portainer_data:

networks:
  security-network:
    driver: bridge


